name: 4. Build Loop
run-name: Build Loop ${{ github.ref_name }}
on:
  workflow_dispatch:
  
  ## Remove the "#" sign from the beginning of the line below to get automated builds on push (code changes in your repository)
  #push:

  ## Remove the "#" sign from the beginning of the two lines below to get automated builds every two months
  #schedule:
    #- cron: '0 17 1 */2 *' # Runs at 17:00 UTC on the 1st in Jan, Mar, May, Jul, Sep and Nov.

jobs:
  secrets:
    uses: ./.github/workflows/validate_secrets.yml
    secrets: inherit
    
  build:
    needs: secrets
    runs-on: macos-12
    steps:
      # Uncomment to manually select latest Xcode if needed
      - name: Select Latest Xcode
        run: "sudo xcode-select --switch /Applications/Xcode_14.1.app/Contents/Developer"

      # Checks-out the repo
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      # Customize Loop: Download and apply patches
      - name: Customize Loop
        run: |

          # For each patch, edit comment line (keep the #) then update curl (and remove the #)

          # Submodule Loop patches:
          # Loop: Filename: customization details
          #curl https://github.com/username/Loop/commit/SHA-1.patch | git apply -v --directory=Loop

          # Submodule LoopKit patches:
          # LoopKit: Filename: customization details
          #curl https://github.com/username/LoopKit/commit/SHA-1.patch | git apply -v --directory=LoopKit

          # Submodule xxxxx patches: Follow prototype above
      
          # BEGINNING: apply the lnl_patches to the released code
          # See: https://www.loopandlearn.org/main-lnl-patches
          
          # LoopWorkspace commit: Adds xDrip4iOS and GlucoseDirect CGM clients
          # Note - the added submodules must be cloned before the patch will work
          #git clone https://github.com/johandegraeve/xdrip-client-swift-1.git xdrip-client-swift
          #git clone https://github.com/creepymonster/GlucoseDirectClient.git GlucoseDirectClient
          # This patch configures LoopWorkspace to use the added CGM submodules
          #curl https://github.com/loopnlearn/LoopWorkspace/commit/4092277a21fa44a1258b693a5fbcce4d8d9dbd17.patch | git apply

          # LoopWorkspace commit: Merge pull request to add LoopnLearn logo (from MikePlante1)
          #curl https://github.com/loopnlearn/LoopWorkspace/commit/7c1dd02e74508a171128de85741e44b09ccee118.patch | git apply

          # This applies CustomTypeOne LoopPatches to released submodules Loop and LoopKit
          # See: https://www.loopandlearn.org/custom-type-one-loop-patches
          curl https://raw.githubusercontent.com/CustomTypeOne/LoopPatches/dev/LoopWorkspace.patch | git apply

          # END: lnl_patches now applied to the released code
          
          # additional patches can be put below - make sure columns line up
             
          # Loop: Increase future carb time limit to 4 hours from 1 hour default
          curl https://github.com/loopnlearn/Loop/commit/a974b6749ef4506ca679a0061c260dabcfbf9ee2.patch | git apply --directory=Loop
            
          # Loop: LoopConstants: Limit carb entry to 99 and shows warning if over 49 g
          curl https://github.com/loopnlearn/Loop/commit/d9939c65a6b2fc088ee5acdf0d9dc247ad30986c.patch | git apply --directory=Loop
                  
          # LoopKit: Modify the override sensitivity range to 50% to 200%, allow 5% steps
          curl https://github.com/loopnlearn/LoopKit/commit/f35654104f70b7dc70f750d129fbb338b9a4cee0.patch | git apply --directory=LoopKit
                  
          # CAGE: upload pod start to Nightscout, Updates both OmniKit (Eros) and OmniBLE (DASH)
          curl https://raw.githubusercontent.com/loopnlearn/loopbuildscripts/main/patch/cage.patch | git apply
                  
          # SAGE: upload Dexcom sensor start to Nightscout
          #curl https://raw.githubusercontent.com/loopnlearn/loopbuildscripts/main/patch/g6g7_sage.patch | git apply
                  
          # Set Default selection to upload Dexcom readings to remote services (Nightscout and Tidepool)
          curl https://raw.githubusercontent.com/loopnlearn/loopbuildscripts/main/patch/g6g7_upload_readings.patch | git apply
          
          # OmniBLE/OmnipodCommon/Pod.swift: increase pod insertion insulin from 0.0 to 0.35
          curl https://github.com/shake73/OmniBLE/commit/e59680d00edcb3fb38fa39b7b76e37d0445202b7.patch | git apply --directory=OmniBLE
    
          # Add Adult-Child insulin model
          #curl https://github.com/shake73/LoopWorkspace/commit/981923fff9ebae936f907f3faaa794e34708ec5d.patch | git apply --directory=LoopWorkspace
 
          # Add panda icons
          #curl https://github.com/shake73/LoopWorkspace/commit/66669efabc1a9901cd647196053b473ca0de16f8.patch | git apply --directory=LoopWorkspace
    
      # Patch Fastlane Match to not print tables
      - name: Patch Match Tables
        run: find /usr/local/lib/ruby/gems -name table_printer.rb | xargs sed -i "" "/puts(Terminal::Table.new(params))/d"
      
      # Build signed Loop IPA file
      - name: Fastlane Build & Archive
        run: fastlane build_loop
        env:
          TEAMID: ${{ secrets.TEAMID }}
          GH_PAT: ${{ secrets.GH_PAT }}
          FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
          FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
          FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      
      # Upload to TestFlight
      - name: Fastlane upload to TestFlight
        run: fastlane release
        env:
          TEAMID: ${{ secrets.TEAMID }}
          GH_PAT: ${{ secrets.GH_PAT }}
          FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
          FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
          FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      # Upload Build artifacts
      - name: Upload build log, IPA and Symbol artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            artifacts
            buildlog
